import type { Metadata } from "next";
import { Geist_Mono, Lato } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/layout";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sigmar = Lato({
  variable: "--font-sigmar",
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex h-full">
      <body className={`${geistMono.variable} ${sigmar.variable} antialiased flex-1 flex flex-col`}>
        <div className="flex-1 flex flex-col">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
