import type { Metadata } from "next";
import { Geist_Mono, Lato } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import { Header } from "@/components/layout";
import { Footer } from "@/components/layout/footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sigmar = Lato({
  variable: "--font-sigmar",
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex h-full">
      <head>
        <script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="5894ce05-d989-454f-bbbb-aba23e034328"
        ></script>
        <meta name="google-adsense-account" content="ca-pub-7098826907138268" />
      </head>
      <body className={`${geistMono.variable} ${sigmar.variable} antialiased flex-1 flex flex-col`}>
        <div className="flex-1 flex flex-col">
          <Header />
          <Analytics />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
