export const CACHE_TAGS = {
  github: "github",
  package: "package",
  ovsIncludingTransitive: "ovs_with_transitive",
  ovsWithoutTransitive: "ovs_without_transitive",
  specificVulnerability: "vln_specific",
  ovsPackageAllVersions: "ovs_package_versions",
  packageDownloadStats: "package_download_stats",
  trends: "trends",
  aiPackageSummary: "ai_package_summary",
  aiReleaseFrequencySummary: "ai_release_frequency_summary",
  aiOverallVersionsSummary: "ai_overall_versions_summary",
  aiPopularitySummary: "ai_popularity_summary",
  aiPackageSecuritySummary: "ai_security_summary",
  aiSpecificVersionSummary: "ai_specific_version_summary",
} as const;
